# Choose the Node.js base image

# Set the working directory inside the container

# Copy package.json and package-lock.json

# Install dependencies

# Bundle app source

# Your app binds to port 8080, so you'll use the EXPOSE instruction to have it mapped by the docker daemon

